### ISSUE TITLE
icebreaker.py error

### ISSUE THREAD

**Issue by dadede** [icebreaker-fpga/icebreaker-litex-examples#3]
After cloning, I run the icebreaker.py script in the soc folder with both --debug and --flash option, then with either and with none. I get the following error

Warning: Wire top.uartwishbonebridge_state has an unprocessed 'init' attribute.
Warning: Wire top.wb2csr_next_state has an unprocessed 'init' attribute.
unrecognised option '--pre-pack'
Traceback (most recent call last):
  File "./icebreaker.py", line 243, in <module>
    main()
  File "./icebreaker.py", line 234, in main
    builder.build()
  File "/home/unix/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/builder.py", line 204, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/home/unix/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/soc.py", line 897, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/unix/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/platform.py", line 34, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/unix/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/icestorm.py", line 194, in build
    _run_script(script)
  File "/home/unix/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/icestorm.py", line 127, in _run_script
    raise OSError("Subprocess failed")
OSError: Subprocess failed

Can anyone please help me figure this out? Efforts are greatly appreciated!

**Comment by daveshah1** [comment]
`unrecognised option '--pre-pack'` sounds like you have very old (over a year) nextpnr that will need to be updated

**Comment by dadede** [comment]
Thanks David. I had actually installed nextpnr using the `cmake -DARCH=ice40 -DBUILD_PYTHON=OFF -DBUILD_GUI=OFF . ` option since I was getting cmake errors about not being able to find python. I have reinstalled but I'm still getting the error, is there something I may have missed during installation?

**Comment by daveshah1** [comment]
Oh, the `--pre-pack` command will be missing because you haven't built with Python. Can you try and figure out why it isn't finding Python? What OS are you on?

**Comment by daveshah1** [comment]
Alternatively, for a quick test (losing proper clock constraints) you could remove `--pre-pack {build_name}_pre_pack.py` from https://github.com/icebreaker-fpga/icebreaker-litex-examples/blob/master/soc/icebreaker.py#L193

**Comment by dadede** [comment]
I'm using Ubuntu 18.04.1. When building nextpnr I came across this error and had to build without python... [https://github.com/YosysHQ/nextpnr/issues/215#issue-400929052](url)
I can't seem to figure out why exactly python is not found but from my research on the internet, it seems that an error arises with Boost finding Python when cmake is run to build nextpnr.
`cmake -DARCH=ice40 .` results in No version of Boost::Python 3.x could be found.

If i go ahead to remove `--pre-pack {build_name}_pre_pack.py` from that line, does it cause problems with the building the SoC or affect it's performance since proper clock constraints are lost?

**Comment by daveshah1** [comment]
Can you post the exact problem you see as there are a few different things described in that issue? A warning about not finding Python is part of the CMake search process and not a problem, on the other hand an error needs to be fixed.

Removing the constraints shouldn't be a major problem in this case.

**Comment by disdi** [comment]
Still getting the same error on Ubuntu 20.04 with --debug option .
--flash works for me.

ERROR: Failed to expand region (0, 0) |_> (25, 31) of 5324 ICESTORM_LCs
0 warnings, 1 error
Traceback (most recent call last):
  File "icebreaker.py", line 246, in <module>
    main()
  File "icebreaker.py", line 236, in main
    builder.build()
  File "/lhome/saksinh/disdi/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/builder.py", line 315, in build
    vns = self.soc.build(build_dir=self.gateware_dir, **kwargs)
  File "/lhome/saksinh/disdi/icebreaker-litex-examples/soc/deps/litex/litex/soc/integration/soc.py", line 1131, in build
    return self.platform.build(self, *args, **kwargs)
  File "/lhome/saksinh/disdi/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/platform.py", line 43, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/lhome/saksinh/disdi/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/icestorm.py", line 206, in build
    _run_script(script)
  File "/lhome/saksinh/disdi/icebreaker-litex-examples/soc/deps/litex/litex/build/lattice/icestorm.py", line 146, in _run_script
    raise OSError("Error occured during Yosys/Nextpnr's script execution.")
OSError: Error occured during Yosys/Nextpnr's script execution.

**Comment by disdi** [comment]
I think the Icebreaker does not have enough LUTs to have gateware with debug build
